### PR TITLE
User & Playlist management

### LINKED ISSUE #2: Add authentication and protect the routes
Protect Playlist and Liking features with Authentication

### LINKED ISSUE #5: create backend to manage users and video data

### PR DESCRIPTION
**Pull request by hntejas**

### CODE REVIEW

**Comment by MadhushreeKunder** [comment]
@hntejas Your Dev Stream looks really good! The UI is clean and the loading animation/gif is also good!
A couple of small changes I'd like to suggest is: 
1. On the home page, where all the videos are displayed, there is some extra space on the right-hand side(marked in yellow):
Inkedtejad dev stream_LI
So you can adjust the videos in a way that space reduces, and you can also add some spacing on the left-hand side (marked in blue)
2. For the home icon in the side navbar, you have used a filled icon, whereas for liked videos, it is an outline icon, so you can keep all your icons filled or outlined, consistency will good. 
3. When the user logs out, can you display a prompt or modal saying that the user has logged out?

**Comment by hntejas** [comment]
> @hntejas Your Dev Stream looks really good! The UI is clean and the loading animation/gif is also good!
> A couple of small changes I'd like to suggest is:
> 
> 1. On the home page, where all the videos are displayed, there is some extra space on the right-hand side(marked in yellow):
>    Inkedtejad dev stream_LI
>    So you can adjust the videos in a way that space reduces, and you can also add some spacing on the left-hand side (marked in blue)
> 2. For the home icon in the side navbar, you have used a filled icon, whereas for liked videos, it is an outline icon, so you can keep all your icons filled or outlined, consistency will good.
> 3. When the user logs out, can you display a prompt or modal saying that the user has logged out?

@MadhushreeKunder  Thanks for taking the time to review, I've applied all the changes that were suggested. Please do take a look at it.

**Comment by MadhushreeKunder** [comment]
Yes, it looks good now, just one last suggestion: If you also put some padding between the 4 columns on the home page, it would look better and neater.  @hntejas

**Comment by hntejas** [comment]
> Yes, it looks good now, just one last suggestion: If you also put some padding between the 4 columns on the home page, it would look better and neater. @hntejas

@MadhushreeKunder  I have done the changes as suggested.

**Review by MadhushreeKunder — APPROVED** [review]
Good job!

**Pull request merged**
